allowBuilds:
  '@whiskeysockets/baileys': true
  esbuild: true
  msw: true
  protobufjs: true
  sharp: true
minimumReleaseAgeExclude:
  - '@better-auth/core@1.6.16'
  - '@better-auth/drizzle-adapter@1.6.16'
  - '@better-auth/kysely-adapter@1.6.16'
  - '@better-auth/memory-adapter@1.6.16'
  - '@better-auth/mongo-adapter@1.6.16'
  - '@better-auth/prisma-adapter@1.6.16'
  - '@better-auth/telemetry@1.6.16'
  - '@better-fetch/fetch@1.2.2'
  - better-auth@1.6.16
  - better-call@1.3.6
